# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ji1cr85TWC5BLuOq4TjtxDRzsukBCa9v6DS22CK7/PCWP9SavCEI6iyTT6OiRSqIaC2xrTrXKf7mICtGlEqCKq/va8LFOoDDmLJTKLpFe/9YzM5654XUOyp3aQSauwPC43A3+NEy3h1oe0z1TmquaiC2/MQN2Ic7dO/llPVvm/iYKqixMlVU3JFlVsykrr7oh/dZ17ewtm1gxvhh5kwqAtemx8FlGddm8QAwydth8P1DZVQWFiMlXRM9FBzfHxhtidOHHV9kcJygDBF/CJRSFupZWkDqL2HJLwBi4sgxzmiUp9ho8fjnUzlfbDBU5m3ke0NIzutFACFA81T4POAHMAApk/6VCDMK2Po9ZP8mZQojSXyR9N71pN5a4pg+SshoMfMxYkBQqroq2j+txSFK+K2XYuiCBoZssx1v4lxY3fIvQKDIJmE1I81AWI21wEdAgxsyYGwet+ePUQ76rx7RB0s5coJVuWggb/atsGNNT4P7DEcKv7vFaaTA71u9458eg7mM1gh/lxVHHGOl+TJBOM2GkMTAnmB1OyNNtMRJ13uaxhf6I2S4t5eDKzwS3ZJFK4nPmoI6VJoenr1Yw/0tkm1f8C98u8CAoKdKH5dzpHWaG04AmXgxyeun+63a5oYC9KOeiWVTk/VB3dmuD5uJGXJDKVf6dNSL/x4EpodwTPg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
