travis:
  secure:
    BINSTAR_TOKEN: kupvrh4yJgXWc+b2PQtzwNRzaR1zmqoa3SUY1rOjx4PuZFLnkHICNfIeha20w5ZPIaTDKaBwtZE4hOIlyumB9GWTJatSQwrPWOlh5enYr+7Hv4kLjqLV7aECYtBs5cABpXtaII2hujcnLBqnv6II0dawCeGbmyTC+Pu3+rzFGIVvEsG94TSDKOvUSpN7bbBhmhWpGmhn2L9//of5AV53Oq/HkaZ2pqFihvFuhiDHw2Xhm38cy0crsxkgvHz6xDwD9IL6Vj++3mPCg2yJfJyYKmrS1+wC6IJk3kjOj50XjCyJgJGjq8Om5c8h6H2432rirgMYh2vz5c1kYrscfN6yCQvnDk+/FSVqdgAT5qMHwDHmaqx9Kll1WnTOYonZcQBqUW1T8YzhY/j/OkkuDEeeDRKkVfKl5W2uhO0fx2/O54favrJNhvd/27PMLEFx88qDbWq7R+ixvNSAI7Ahx6i5L9qQex9aSzGLIXUWdoi71voIO0RsJz2UA9okcai09QCUJcT6Wihl1aF7sl0yiZI1Jdo2Ub1zBm5kPMAX5mn1rUZV0WJvkFciqZ0colQeT2Jf0zs8aRTBh1yFgfBk+LHBYx6bmLDgOIr/L1SXhB0+R6wJBvGKjv6MQrx7gConhcD8pI+SqyCpWsBAhbyWQ+bdn2YWoxzf/g9C176qDqPKa4g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
